version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/pg_data
    networks:
      - backend
    restart: always

  graphql:
    build: ./src/app
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports:
      - "4000:4000"
    volumes:
      - ./src/app/index.js:/app/index.js
    depends_on:
      - postgres
    networks:
      - backend
    restart: always

networks:
  backend: